spring:
  application:
    name: cicdapp

  # 데이터베이스 연결 설정
  datasource:
    # 💡 도커 컴포즈가 환경변수를 주입해주면 그 값을 쓰고, 없으면 로컬(localhost)을 바라봅니다.
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:cicdapp_db}?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    # 💡 GitHub Secrets에서 파생되어 도커 컴포즈가 넘겨줄 실제 운영 DB 비밀번호를 받습니다.
    password: ${DB_PASSWORD:}

  # JPA 하이버네이트 설정
  jpa:
    hibernate:
      # 💡 초기 테이블 생성 및 시드 데이터 적재 후 재부팅 시 데이터가 날아가지 않도록 update를 사용합니다.
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect